function handel = func_AHG_parameters(site_no,... % USGS site number
    subsample_size,... % Number of folding in Modified Cross-validation Regression Diagnostic
    computation_unit,... % Computation unit in plotting and outcome AHG table
    starting_path) % Path of main directory
%%%%% getting I/O directories %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
input_directory = fullfile(starting_path,'Imported_USGS_Data');
output_directory = fullfile(starting_path,'Imported_USGS_Data');
%%%%%
functions_directory_name = starting_path;
%%%%%
input_files = dir(input_directory);
%%%%%
input_fileIndex = find(~[input_files.isdir]);
%%%%% Assigining the computational unit %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
switch computation_unit
    
    case 'English'
        cfs_to_cms_unit_conv = 1;
        ft_to_m_unit_conv = 1;
        discharge_unit_label = '({ft^3}/s)';
        gageheight_unit_label = '(ft)';
        Output_suffix = '_bankfull_Eng';
        velocity_unit_label = '(ft/s)';
        area_unit_label = '({ft^2})';
        topwidth_unit_label = '(ft)';
        mean_depth_unit_label = '(ft)';
    case 'SI'
        cfs_to_cms_unit_conv = 0.028316847;
        ft_to_m_unit_conv = 0.3048;
        discharge_unit_label = '({m^3}/s)';
        gageheight_unit_label = '(m)';
        Output_suffix = '_bankfull_SI';
        velocity_unit_label = '(m/s)';
        area_unit_label = '({m^2})';
        topwidth_unit_label = '(m)';
        mean_depth_unit_label = '(m)';
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Graphical Attributes %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% subsample_size = 10;
axes_FontSize = 10;
legend_font_size = 8;
legend_marker_size = 14;
Title_String_size = 11;
xlabel_FontSize = 10;
ylabel_FontSize = 10;
X_exploratory_steps = 0.01;
original_point_shape_size = 8;
Nonoutlier_point_shape_size = 10;
all_point_color = [0.75 0.75 0.75];
proper_bounds_point_color = [0 0.5 0.72];
line_width = 1.5;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Desired Daily Data and Surveyed Data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
prefix_string = site_no; %'02462951';
file_names_DD = struct2cell(input_files);
file_names_DD = file_names_DD(1,3:end)';
file_names_SD = struct2cell(input_files);
file_names_SD = file_names_SD(1,3:end)';
suffix_string_DD = '_DailyPeaks_Data.mat';
suffix_string_SD = '_Surveyed_Data.mat';
desired_file_name_DD = {strcat(prefix_string,suffix_string_DD)};
desired_file_name_SD = {strcat(prefix_string,suffix_string_SD)};
i_DailyData = strcmp(desired_file_name_DD,file_names_DD);
i_SurvayedData = strcmp(desired_file_name_SD,file_names_SD);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Table of AHG relation parameters - Initiation %%%%%%%%%%%%%%%%%%%%%%%%%
Surveyed_Data_Raw_Varialbe_Name = 'Surveyed_Data_Cell_Raw';
Title_String_suffix = '';

USGS_Data_Assembled_Fields_titles_proper_sites = {'agency_cd',...
    'site_no','lat_va',...
    'long_va','drain_area_va',... 
    'SD Reliable_Flow_Meas_Counts','SD Full_TimeSeries_Meas_Counts',...
    'sd_gagehei_disch_exp',...
    'sd_gagehei_disch_coeff',...
    'sd_gagehei_disch_offset','sd_gagehei_disch_R2',...
    'sd_vel_disch_exp','sd_vel_disch_coeff','sd_vel_disch_R2',...
    'sd_area_disch_exp','sd_area_disch_coeff','sd_area_disch_R2',...
    'sd_width_disch_exp','sd_width_disch_coeff','sd_width_disch_R2',...
    'sd_mdepth_disch_exp','sd_mdepth_disch_coeff','sd_mdepth_disch_R2',...
    'AHG Exponents Sum','AHG Coeff. Product',...
    'Alpha Point Estimate','Beta Point Estimate',...
    'p Exponent Point Estimate',...
    'manning_energyslope_product'};

USGS_Data_AHG_Table = ...
    USGS_Data_Assembled_Fields_titles_proper_sites;
USGS_Data_Assembled_Fields_titles_proper_sites = ...
    strcat(USGS_Data_Assembled_Fields_titles_proper_sites(1,:),...
    Title_String_suffix);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
warning ('off','all');
%%% Initialization of the Surveyed Data
input_fileName_surveyed_data = input_files(...
    input_fileIndex(i_SurvayedData)).name;
[~,NAME_surveyed_data,~] = fileparts(input_fileName_surveyed_data);
NAME_surveyed_data_parts = strread(NAME_surveyed_data,'%s','delimiter','_');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
input_fileName_daily_data = ...
    input_files(input_fileIndex(i_DailyData)).name;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Loading "surveyed_data_raw" file
path_surveyed_data = input_directory;
cd(path_surveyed_data)
load(input_fileName_surveyed_data,Surveyed_Data_Raw_Varialbe_Name);
cd(starting_path)
%%% Checking if the loaded "surveyed_data_raw" file has larger
%%% 3 rows of data
if size(Surveyed_Data_Cell_Raw,1) > 3
    cd(functions_directory_name)
    [Surveyed_Data_Cell_Measurement_Rated,...
        Desired_Columns_Titles_Indecies] = ...
        func_Surveyed_Data_revised(Surveyed_Data_Cell_Raw);
    cd(starting_path)
    clear Surveyed_Data_Cell_Raw
else
    error('The imported data of the current USGS station does not contain field surveyed data.');
end
if size(Surveyed_Data_Cell_Measurement_Rated,1) < 4
    error('The imported data of the current USGS station does not contain field surveyed data.');
end
path_daily_data = input_directory;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% loading "daily_data_raw_proper" file
%%% NOTE: units are in original English units, and they will be
%%% converted to SI in upcoming lines
cd(path_daily_data)
load(input_fileName_daily_data,'BankFull_Discharge',...
    'Inxd_bankfull',...
    'index_Unsorted_Discharge_peak',...
    'Discharge_GageHeight_Cell_Proper');
cd(starting_path)
%%% 1.1 Surveyed Data Gage Height vs. Discharge Plot %%%%%%%%%%%%%%%%%%%%%%
%%%% 1.1.1 Detecting within bankfull flow indicies in surveyed data
% Assigning Computational Unit
switch computation_unit
    case 'English'
        Beyond_Bankfull_Indx_Surveyed_Data = ...
            find(cell2mat(Surveyed_Data_Cell_Measurement_Rated(2:end,24))>...
            BankFull_Discharge/cfs_to_cms_unit_conv)+1; % +1 is added accounting for cell header
    case 'SI'
        Beyond_Bankfull_Indx_Surveyed_Data = ...
            find(cell2mat(Surveyed_Data_Cell_Measurement_Rated(2:end,24))>...
            BankFull_Discharge/cfs_to_cms_unit_conv)+1; % +1 is added accounting for cell header
end
Surveyed_Data_Cell_Measurement_Rated_Bankfull = ...
    Surveyed_Data_Cell_Measurement_Rated;
Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    Beyond_Bankfull_Indx_Surveyed_Data,:) = [];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
gage_height_index_column = Desired_Columns_Titles_Indecies{2,1};
discharge_index_column = Desired_Columns_Titles_Indecies{2,2};
X_exploratory_surveyed_data_discharge_bankfull = ...
    cfs_to_cms_unit_conv*...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(2:end,...
    discharge_index_column));
Y_response_surveyed_data_gage_height_bankfull = ...
    ft_to_m_unit_conv*...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(2:end,...
    gage_height_index_column));
SD_X_positive_indicies = ...
    X_exploratory_surveyed_data_discharge_bankfull > 0;
SD_Y_positive_indicies = ...
    Y_response_surveyed_data_gage_height_bankfull > 0;
SD_positive_indicies_dum = double(SD_X_positive_indicies)+...
    double(SD_Y_positive_indicies)-1;
SD_positive_indicies_dum(SD_positive_indicies_dum(:)==-1)=0;
%%% verification for nan values %%%
X_verification_nan = double(~isnan(X_exploratory_surveyed_data_discharge_bankfull));
X_verification_inf = double(~isinf(X_exploratory_surveyed_data_discharge_bankfull));
Y_verification_nan = double(~isnan(Y_response_surveyed_data_gage_height_bankfull));
Y_verification_inf = double(~isinf(Y_response_surveyed_data_gage_height_bankfull));
verification_indx = ...
    (X_verification_nan+...
    X_verification_inf+...
    Y_verification_nan+...
    Y_verification_inf)==4;
SD_positive_indicies_dum_2 = ...
    double(SD_positive_indicies_dum)+double(verification_indx)-1;
SD_positive_indicies_dum_2(...
    (SD_positive_indicies_dum_2==-1))=0;
SD_positive_indicies = logical(SD_positive_indicies_dum_2);
if size(Surveyed_Data_Cell_Measurement_Rated_Bankfull,1)<10 || ...
        length(find(SD_positive_indicies)) < 10
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. stage-hieght measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
for I = 1:1
    cd(functions_directory_name)
    %%% Leave-one-out/K-Fold Cross-Validation Analysis
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    foldnum=[2,5,10,20,50,75,100,1];
    KFold = {'2-Fold MCV';'5-Fold MCV';'10-Fold MCV';'20-Fold MCV';'50-Fold MCV';'75-Fold MCV';'100-Fold MCV';'LOO MCV'};
    counter0 = 1;
    for i_folding = 1:8
        if i_folding==8
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_surveyed_data_gage_height_bankfull(SD_positive_indicies),... % dependent variable
                'power2',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'LeaveOut',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                []); % 'KFold' value foldnum(i_folding)
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        else
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_surveyed_data_gage_height_bankfull(SD_positive_indicies),... % dependent variable
                'power2',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'KFold',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                foldnum(i_folding)); % 'KFold' value
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        end
        counter0 = counter0+1;
    end
    param_set_statistics_table = [...
        param_set_statistics_table_scratch(1,:);...
        param_set_statistics_table];
    param_set_statistics_table_scores_scratch = (...
        (cell2mat(param_set_statistics_table(2:end,2))/max(cell2mat(param_set_statistics_table(2:end,2))))+... %R2
        (1-(cell2mat(param_set_statistics_table(2:end,3))/max(cell2mat(param_set_statistics_table(2:end,3)))))+... % Bias Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,4)))/max(abs(cell2mat(param_set_statistics_table(2:end,4))))))+... % Bias Accuracy
        (1-(cell2mat(param_set_statistics_table(2:end,5))/max(cell2mat(param_set_statistics_table(2:end,5)))))+... % Invertibility Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,6)))/max(abs(cell2mat(param_set_statistics_table(2:end,6)))))))/5; % Invertibility Accuracy
    param_set_statistics_table = [...
        ['Partitioning Type';KFold],...
        ['Scaled Score (0-1)';num2cell(param_set_statistics_table_scores_scratch)],...
        param_set_statistics_table];
    [~,param_set_statistics_table_bestPartiType_I] = max(param_set_statistics_table_scores_scratch);
    param_set_statistics_table_bestPartiType_I = ...
        param_set_statistics_table_bestPartiType_I+1;
    param_set_statistics_table_bestPartiType = [...
        param_set_statistics_table(1,:);...
        param_set_statistics_table(...
        param_set_statistics_table_bestPartiType_I,:)];
    %%%% Creating symbolic cfit function %%%%
    x_scratch = linspace(0.1,1,10)';
    y_scratch = x_scratch.^1 + randn(length(x_scratch),1);
    [f_fullts_best_model_SD_StgHght,~]=fit(x_scratch,y_scratch,'power2');
    warning('off')
    f_fullts_best_model_SD_StgHght.a = param_set_statistics_table_bestPartiType{2,3}(1);
    f_fullts_best_model_SD_StgHght.b = param_set_statistics_table_bestPartiType{2,3}(2);
    f_fullts_best_model_SD_StgHght.c = param_set_statistics_table_bestPartiType{2,3}(3);
    clear x_scratch y_scratch ...
        param_set_statistics_table_bestPartiType ...
        param_set_statistics_table
    %%% Regression Diagnostic Analysis to reselect peak flows
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [X_exploratory_bankfull_fullts_Nonoutlier_SD,...
        StageHeight_response_bankfull_fullts_Nonoutlier_SD,~]=func_RegressionDiagnostic(...
        X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),...
        Y_response_surveyed_data_gage_height_bankfull(SD_positive_indicies),...
        f_fullts_best_model_SD_StgHght);
    cd(starting_path)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Index_StageHeight_Nonoutlier_SD = ...
        find(ismember(Y_response_surveyed_data_gage_height_bankfull,...
        StageHeight_response_bankfull_fullts_Nonoutlier_SD));
end
%%% 1.2. Surveyed Data Discharge vs. Velocity %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
velocity_index_column = Desired_Columns_Titles_Indecies{2,5};
Y_response_Velocity_surveyed_data_bankfull = ...
    ft_to_m_unit_conv*...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    2:end,velocity_index_column));
SD_X_positive_indicies = ...
    X_exploratory_surveyed_data_discharge_bankfull > 0;
SD_Y_positive_indicies = ...
    Y_response_Velocity_surveyed_data_bankfull > 0;
SD_positive_indicies_dum = double(SD_X_positive_indicies)+...
    double(SD_Y_positive_indicies)-1;
SD_positive_indicies_dum(SD_positive_indicies_dum(:)==-1)=0;
%%% verification for nan values %%%
X_verification_nan = double(~isnan(X_exploratory_surveyed_data_discharge_bankfull));
X_verification_inf = double(~isinf(X_exploratory_surveyed_data_discharge_bankfull));
Y_verification_nan = double(~isnan(Y_response_Velocity_surveyed_data_bankfull));
Y_verification_inf = double(~isinf(Y_response_Velocity_surveyed_data_bankfull));
verification_indx = ...
    (X_verification_nan+...
    X_verification_inf+...
    Y_verification_nan+...
    Y_verification_inf)==4;
SD_positive_indicies_dum_2 = ...
    double(SD_positive_indicies_dum)+double(verification_indx)-1;
SD_positive_indicies_dum_2(...
    (SD_positive_indicies_dum_2==-1))=0;
SD_positive_indicies = logical(SD_positive_indicies_dum_2);
if length(find(SD_positive_indicies)) < 10
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. velocity measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
for I = 1:1
    cd(functions_directory_name)
    %%% Leave-one-out/K-Fold Cross-Validation Analysis
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    foldnum=[2,5,10,20,50,75,100,1];
    KFold = {'2-Fold MCV';'5-Fold MCV';'10-Fold MCV';'20-Fold MCV';'50-Fold MCV';'75-Fold MCV';'100-Fold MCV';'LOO MCV'};
    counter0 = 1;
    for i_folding = 1:8
        if i_folding==8
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Velocity_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'LeaveOut',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                []); % 'KFold' value foldnum(i_folding)
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        else
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Velocity_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'KFold',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                foldnum(i_folding)); % 'KFold' value
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        end
        counter0 = counter0+1;
    end
    param_set_statistics_table = [...
        param_set_statistics_table_scratch(1,:);...
        param_set_statistics_table];
    param_set_statistics_table_scores_scratch = (...
        (cell2mat(param_set_statistics_table(2:end,2))/max(cell2mat(param_set_statistics_table(2:end,2))))+... %R2
        (1-(cell2mat(param_set_statistics_table(2:end,3))/max(cell2mat(param_set_statistics_table(2:end,3)))))+... % Bias Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,4)))/max(abs(cell2mat(param_set_statistics_table(2:end,4))))))+... % Bias Accuracy
        (1-(cell2mat(param_set_statistics_table(2:end,5))/max(cell2mat(param_set_statistics_table(2:end,5)))))+... % Invertibility Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,6)))/max(abs(cell2mat(param_set_statistics_table(2:end,6)))))))/5; % Invertibility Accuracy
    param_set_statistics_table = [...
        ['Partitioning Type';KFold],...
        ['Scaled Score (0-1)';num2cell(param_set_statistics_table_scores_scratch)],...
        param_set_statistics_table];
    [~,param_set_statistics_table_bestPartiType_I] = max(param_set_statistics_table_scores_scratch);
    param_set_statistics_table_bestPartiType_I = ...
        param_set_statistics_table_bestPartiType_I+1;
    param_set_statistics_table_bestPartiType = [...
        param_set_statistics_table(1,:);...
        param_set_statistics_table(...
        param_set_statistics_table_bestPartiType_I,:)];
    %%%% Creating symbolic cfit function %%%%
    x_scratch = linspace(0.1,1,10)';
    y_scratch = x_scratch.^1 + randn(length(x_scratch),1);
    [f_fullts_best_model_SD_Vel,~]=fit(x_scratch,y_scratch,'power1');
    warning('off')
    f_fullts_best_model_SD_Vel.a = param_set_statistics_table_bestPartiType{2,3}(1);
    f_fullts_best_model_SD_Vel.b = param_set_statistics_table_bestPartiType{2,3}(2);
    clear x_scratch y_scratch...
        param_set_statistics_table_bestPartiType...
        param_set_statistics_table
    %%% Regression Diagnostic Analysis to reselect peak flows
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [X_exploratory_bankfull_fullts_Nonoutlier_SD,...
        Velocity_response_bankfull_fullts_Nonoutlier_SD,...
        Index_Velocity_Nonoutlier_SD]=func_RegressionDiagnostic(...
        X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),...
        Y_response_Velocity_surveyed_data_bankfull(SD_positive_indicies),...
        f_fullts_best_model_SD_Vel);
    cd(starting_path)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Index_Velocity_Nonoutlier_SD = ...
        find(ismember(Y_response_Velocity_surveyed_data_bankfull,...
        Velocity_response_bankfull_fullts_Nonoutlier_SD));
end
%%% 1.3. Surveyed Data Discharge vs. Width %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
TopWidth_index_column = Desired_Columns_Titles_Indecies{2,3};
Y_response_TopWidth_surveyed_data_bankfull = ...
    ft_to_m_unit_conv*...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    2:end,TopWidth_index_column));
SD_X_positive_indicies = ...
    X_exploratory_surveyed_data_discharge_bankfull > 0;
SD_Y_positive_indicies = ...
    Y_response_TopWidth_surveyed_data_bankfull > 0;
SD_positive_indicies_dum = double(SD_X_positive_indicies)+...
    double(SD_Y_positive_indicies)-1;
SD_positive_indicies_dum(SD_positive_indicies_dum(:)==-1)=0;
%%% verification for nan values %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
X_verification_nan = double(~isnan(X_exploratory_surveyed_data_discharge_bankfull));
X_verification_inf = double(~isinf(X_exploratory_surveyed_data_discharge_bankfull));
Y_verification_nan = double(~isnan(Y_response_TopWidth_surveyed_data_bankfull));
Y_verification_inf = double(~isinf(Y_response_TopWidth_surveyed_data_bankfull));
verification_indx = ...
    (X_verification_nan+...
    X_verification_inf+...
    Y_verification_nan+...
    Y_verification_inf)==4;
SD_positive_indicies_dum_2 = ...
    double(SD_positive_indicies_dum)+double(verification_indx)-1;
SD_positive_indicies_dum_2(...
    (SD_positive_indicies_dum_2==-1))=0;
SD_positive_indicies = logical(SD_positive_indicies_dum_2);
if length(find(SD_positive_indicies)) < 10
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. top-width measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
for I = 1:1
    cd(functions_directory_name)
    %%% Leave-one-out/K-Fold Cross-Validation Analysis
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    foldnum=[2,5,10,20,50,75,100,1];
    KFold = {'2-Fold MCV';'5-Fold MCV';'10-Fold MCV';'20-Fold MCV';'50-Fold MCV';'75-Fold MCV';'100-Fold MCV';'LOO MCV'};
    counter0 = 1;
    for i_folding = 1:8
        if i_folding==8
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_TopWidth_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'LeaveOut',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                []); % 'KFold' value foldnum(i_folding)
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        else
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_TopWidth_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'KFold',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                foldnum(i_folding)); % 'KFold' value
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        end
        counter0 = counter0+1;
    end
    param_set_statistics_table = [...
        param_set_statistics_table_scratch(1,:);...
        param_set_statistics_table];
    param_set_statistics_table_scores_scratch = (...
        (cell2mat(param_set_statistics_table(2:end,2))/max(cell2mat(param_set_statistics_table(2:end,2))))+... %R2
        (1-(cell2mat(param_set_statistics_table(2:end,3))/max(cell2mat(param_set_statistics_table(2:end,3)))))+... % Bias Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,4)))/max(abs(cell2mat(param_set_statistics_table(2:end,4))))))+... % Bias Accuracy
        (1-(cell2mat(param_set_statistics_table(2:end,5))/max(cell2mat(param_set_statistics_table(2:end,5)))))+... % Invertibility Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,6)))/max(abs(cell2mat(param_set_statistics_table(2:end,6)))))))/5; % Invertibility Accuracy
    param_set_statistics_table = [...
        ['Partitioning Type';KFold],...
        ['Scaled Score (0-1)';num2cell(param_set_statistics_table_scores_scratch)],...
        param_set_statistics_table];
    [~,param_set_statistics_table_bestPartiType_I] = max(param_set_statistics_table_scores_scratch);
    param_set_statistics_table_bestPartiType_I = ...
        param_set_statistics_table_bestPartiType_I+1;
    param_set_statistics_table_bestPartiType = [...
        param_set_statistics_table(1,:);...
        param_set_statistics_table(...
        param_set_statistics_table_bestPartiType_I,:)];
    %%%% Creating symbolic cfit function %%%%
    x_scratch = linspace(0.1,1,10)';
    y_scratch = x_scratch.^1 + randn(length(x_scratch),1);
    [f_fullts_best_model_SD_TpWid,~]=fit(x_scratch,y_scratch,'power1');
    warning('off')
    f_fullts_best_model_SD_TpWid.a = param_set_statistics_table_bestPartiType{2,3}(1);
    f_fullts_best_model_SD_TpWid.b = param_set_statistics_table_bestPartiType{2,3}(2);
    clear x_scratch y_scratch...
        param_set_statistics_table_bestPartiType...
        param_set_statistics_table
    %%% Regression Diagnostic Analysis to reselect peak flows
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [X_exploratory_bankfull_fullts_Nonoutlier_SD,...
        TopWidth_response_bankfull_fullts_Nonoutlier_SD,...
        Index_TopWidth_Nonoutlier_SD]=...
        func_RegressionDiagnostic(...
        X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),...
        Y_response_TopWidth_surveyed_data_bankfull(SD_positive_indicies),...
        f_fullts_best_model_SD_TpWid);
    cd(starting_path)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Index_TopWidth_Nonoutlier_SD = ...
        find(ismember(Y_response_TopWidth_surveyed_data_bankfull,...
        TopWidth_response_bankfull_fullts_Nonoutlier_SD));
end
%%% 1.4. Surveyed Data Discharge vs. Area %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Area_index_column = Desired_Columns_Titles_Indecies{2,4};
Y_response_Area_surveyed_data_bankfull = ...
    (ft_to_m_unit_conv^2)*...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    2:end,Area_index_column));
SD_X_positive_indicies = ...
    X_exploratory_surveyed_data_discharge_bankfull > 0;
SD_Y_positive_indicies = ...
    Y_response_Area_surveyed_data_bankfull > 0;
SD_positive_indicies_dum = double(SD_X_positive_indicies)+...
    double(SD_Y_positive_indicies)-1;
SD_positive_indicies_dum(SD_positive_indicies_dum(:)==-1)=0;
%%% verification for nan values %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
X_verification_nan = double(~isnan(X_exploratory_surveyed_data_discharge_bankfull));
X_verification_inf = double(~isinf(X_exploratory_surveyed_data_discharge_bankfull));
Y_verification_nan = double(~isnan(Y_response_Area_surveyed_data_bankfull));
Y_verification_inf = double(~isinf(Y_response_Area_surveyed_data_bankfull));
verification_indx = ...
    (X_verification_nan+...
    X_verification_inf+...
    Y_verification_nan+...
    Y_verification_inf)==4;
SD_positive_indicies_dum_2 = ...
    double(SD_positive_indicies_dum)+double(verification_indx)-1;
SD_positive_indicies_dum_2(...
    (SD_positive_indicies_dum_2==-1))=0;
SD_positive_indicies = logical(SD_positive_indicies_dum_2);
if length(find(SD_positive_indicies)) < 10
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. flow area measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
for I = 1:1
    cd(functions_directory_name)
    %%% Leave-one-out/K-Fold Cross-Validation Analysis
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    foldnum=[2,5,10,20,50,75,100,1];
    KFold = {'2-Fold MCV';'5-Fold MCV';'10-Fold MCV';'20-Fold MCV';'50-Fold MCV';'75-Fold MCV';'100-Fold MCV';'LOO MCV'};
    counter0 = 1;
    for i_folding = 1:8
        if i_folding==8
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Area_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'LeaveOut',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                []); % 'KFold' value foldnum(i_folding)
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        else
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Area_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'KFold',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                foldnum(i_folding)); % 'KFold' value
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        end
        counter0 = counter0+1;
    end
    param_set_statistics_table = [...
        param_set_statistics_table_scratch(1,:);...
        param_set_statistics_table];
    param_set_statistics_table_scores_scratch = (...
        (cell2mat(param_set_statistics_table(2:end,2))/max(cell2mat(param_set_statistics_table(2:end,2))))+... %R2
        (1-(cell2mat(param_set_statistics_table(2:end,3))/max(cell2mat(param_set_statistics_table(2:end,3)))))+... % Bias Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,4)))/max(abs(cell2mat(param_set_statistics_table(2:end,4))))))+... % Bias Accuracy
        (1-(cell2mat(param_set_statistics_table(2:end,5))/max(cell2mat(param_set_statistics_table(2:end,5)))))+... % Invertibility Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,6)))/max(abs(cell2mat(param_set_statistics_table(2:end,6)))))))/5; % Invertibility Accuracy
    param_set_statistics_table = [...
        ['Partitioning Type';KFold],...
        ['Scaled Score (0-1)';num2cell(param_set_statistics_table_scores_scratch)],...
        param_set_statistics_table];
    [~,param_set_statistics_table_bestPartiType_I] = max(param_set_statistics_table_scores_scratch);
    param_set_statistics_table_bestPartiType_I = ...
        param_set_statistics_table_bestPartiType_I+1;
    param_set_statistics_table_bestPartiType = [...
        param_set_statistics_table(1,:);...
        param_set_statistics_table(...
        param_set_statistics_table_bestPartiType_I,:)];
    %%%% Creating symbolic cfit function %%%%
    x_scratch = linspace(0.1,1,10)';
    y_scratch = x_scratch.^1 + randn(length(x_scratch),1);
    [f_fullts_best_model_SD_Area,~]=fit(x_scratch,y_scratch,'power1');
    warning('off')
    f_fullts_best_model_SD_Area.a = param_set_statistics_table_bestPartiType{2,3}(1);
    f_fullts_best_model_SD_Area.b = param_set_statistics_table_bestPartiType{2,3}(2);
    clear x_scratch y_scratch...
        param_set_statistics_table_bestPartiType...
        param_set_statistics_table
    %%% Regression Diagnostic Analysis to reselect peak flows
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [X_exploratory_bankfull_fullts_Nonoutlier_SD,...
        Area_response_bankfull_fullts_Nonoutlier_SD,...
        Index_Area_Nonoutlier_SD]=func_RegressionDiagnostic(...
        X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),...
        Y_response_Area_surveyed_data_bankfull(SD_positive_indicies),...
        f_fullts_best_model_SD_Area);
    cd(starting_path)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Index_Area_Nonoutlier_SD = ...
        find(ismember(Y_response_Area_surveyed_data_bankfull,...
        Area_response_bankfull_fullts_Nonoutlier_SD));
end
%%% 1.5. Surveyed Data Discharge vs. Mean Depth %%%%%%%%%%%%%%%%%%%%%%%%%%%
Y_response_Mean_Depth_surveyed_data_bankfull = ...
    ft_to_m_unit_conv*(...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    2:end,Area_index_column))./...
    cell2mat(Surveyed_Data_Cell_Measurement_Rated_Bankfull(...
    2:end,TopWidth_index_column)));
SD_X_positive_indicies = ...
    X_exploratory_surveyed_data_discharge_bankfull > 0;
SD_Y_positive_indicies = ...
    Y_response_Mean_Depth_surveyed_data_bankfull > 0;
SD_positive_indicies_dum = double(SD_X_positive_indicies)+...
    double(SD_Y_positive_indicies)-1;
SD_positive_indicies_dum(SD_positive_indicies_dum(:)==-1)=0;
%%% verification for nan values %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
X_verification_nan = double(~isnan(X_exploratory_surveyed_data_discharge_bankfull));
X_verification_inf = double(~isinf(X_exploratory_surveyed_data_discharge_bankfull));
Y_verification_nan = double(~isnan(Y_response_Mean_Depth_surveyed_data_bankfull));
Y_verification_inf = double(~isinf(Y_response_Mean_Depth_surveyed_data_bankfull));
verification_indx = ...
    (X_verification_nan+...
    X_verification_inf+...
    Y_verification_nan+...
    Y_verification_inf)==4;
SD_positive_indicies_dum_2 = ...
    double(SD_positive_indicies_dum)+double(verification_indx)-1;
SD_positive_indicies_dum_2(...
    (SD_positive_indicies_dum_2==-1))=0;
SD_positive_indicies = logical(SD_positive_indicies_dum_2);
clear X_verification  Y_verification ...
    X_verification_2  Y_verification_2 ...
    Y_response_Mean_Depth_surveyed_data_dum ...
    verification_indx SD_positive_indicies_dum ...
    SD_positive_indicies_dum_2
if length(find(SD_positive_indicies)) < 10
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. mean depth measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
for I = 1:1
    cd(functions_directory_name)
    %%% Leave-one-out/K-Fold Cross-Validation Analysis
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    foldnum=[2,5,10,20,50,75,100,1];
    KFold = {'2-Fold MCV';'5-Fold MCV';'10-Fold MCV';'20-Fold MCV';'50-Fold MCV';'75-Fold MCV';'100-Fold MCV';'LOO MCV'};
    counter0 = 1;
    for i_folding = 1:8
        if i_folding==8
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Mean_Depth_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'LeaveOut',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                []); % 'KFold' value foldnum(i_folding)
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        else
            [f_final_best_model,... % symbolic function as outcome
                param_set_statistics_table_scratch] = ... % cell structure containing: 'R2','Bias Prec.','Bias Accur.','Invertibility Prec.', and 'Invertibility Accur'
                func_ModifiedCrossValidationEnsemble(...
                X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),... % independent variable
                Y_response_Mean_Depth_surveyed_data_bankfull(SD_positive_indicies),... % dependent variable
                'power1',... % text argument describing type of as fitted power-law curve: 'power1' as f(x) = a*x^b, and 'power2' as f(x) = a*x^b+c
                subsample_size,... % number of ensumbles associated with a particular partitioning (e.g. leave-one-out, 10-folds, etc.)
                'KFold',... % string name of a particular partitioning (e.g. leave-one-out, 10-folds, etc.), indicated as: 'LeaveOut' or 'KFold'
                foldnum(i_folding)); % 'KFold' value
            param_set_statistics_table(counter0,:) = param_set_statistics_table_scratch(2,:);
        end
        counter0 = counter0+1;
    end
    param_set_statistics_table = [...
        param_set_statistics_table_scratch(1,:);...
        param_set_statistics_table];
    param_set_statistics_table_scores_scratch = (...
        (cell2mat(param_set_statistics_table(2:end,2))/max(cell2mat(param_set_statistics_table(2:end,2))))+... %R2
        (1-(cell2mat(param_set_statistics_table(2:end,3))/max(cell2mat(param_set_statistics_table(2:end,3)))))+... % Bias Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,4)))/max(abs(cell2mat(param_set_statistics_table(2:end,4))))))+... % Bias Accuracy
        (1-(cell2mat(param_set_statistics_table(2:end,5))/max(cell2mat(param_set_statistics_table(2:end,5)))))+... % Invertibility Precision
        (1-(abs(cell2mat(param_set_statistics_table(2:end,6)))/max(abs(cell2mat(param_set_statistics_table(2:end,6)))))))/5; % Invertibility Accuracy
    param_set_statistics_table = [...
        ['Partitioning Type';KFold],...
        ['Scaled Score (0-1)';num2cell(param_set_statistics_table_scores_scratch)],...
        param_set_statistics_table];
    [~,param_set_statistics_table_bestPartiType_I] = max(param_set_statistics_table_scores_scratch);
    param_set_statistics_table_bestPartiType_I = ...
        param_set_statistics_table_bestPartiType_I+1;
    param_set_statistics_table_bestPartiType = [...
        param_set_statistics_table(1,:);...
        param_set_statistics_table(...
        param_set_statistics_table_bestPartiType_I,:)];
    %%%% Creating symbolic cfit function %%%%
    x_scratch = linspace(0.1,1,10)';
    y_scratch = x_scratch.^1 + randn(length(x_scratch),1);
    [f_fullts_best_model_SD_Mean_Depth,~]=fit(x_scratch,y_scratch,'power1');
    warning('off')
    f_fullts_best_model_SD_Mean_Depth.a = param_set_statistics_table_bestPartiType{2,3}(1);
    f_fullts_best_model_SD_Mean_Depth.b = param_set_statistics_table_bestPartiType{2,3}(2);
    clear x_scratch y_scratch...
        param_set_statistics_table_bestPartiType...
        param_set_statistics_table
    %%% Regression Diagnostic Analysis to reselect peak flows
    %%%% Over Full Time-Series %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [X_exploratory_bankfull_fullts_Nonoutlier_SD,...
        Mean_Depth_response_bankfull_fullts_Nonoutlier_SD,...
        Index_Mean_Depth_Nonoutlier_SD]=func_RegressionDiagnostic(...
        X_exploratory_surveyed_data_discharge_bankfull(SD_positive_indicies),...
        Y_response_Mean_Depth_surveyed_data_bankfull(SD_positive_indicies),...
        f_fullts_best_model_SD_Mean_Depth);
    cd(starting_path)
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    Index_Mean_Depth_Nonoutlier_SD = ...
        find(ismember(Y_response_Mean_Depth_surveyed_data_bankfull,...
        Mean_Depth_response_bankfull_fullts_Nonoutlier_SD));
end
%%% 2. Finding the indicies of similar indicies of non-outlier values in 
%%% discharge versus stage-height, velocity, top-width, flow area, and 
%%% mean depth 
Cell_Nonoutlier_SD = cell(5,2);
Cell_Nonoutlier_SD{1,1} = length(Index_StageHeight_Nonoutlier_SD);
Cell_Nonoutlier_SD{2,1} = length(Index_Velocity_Nonoutlier_SD);
Cell_Nonoutlier_SD{3,1} = length(Index_Area_Nonoutlier_SD);
Cell_Nonoutlier_SD{4,1} = length(Index_TopWidth_Nonoutlier_SD);
Cell_Nonoutlier_SD{5,1} = length(Index_Mean_Depth_Nonoutlier_SD);
Cell_Nonoutlier_SD{1,2} = Index_StageHeight_Nonoutlier_SD;
Cell_Nonoutlier_SD{2,2} = Index_Velocity_Nonoutlier_SD;
Cell_Nonoutlier_SD{3,2} = Index_Area_Nonoutlier_SD;
Cell_Nonoutlier_SD{4,2} = Index_TopWidth_Nonoutlier_SD;
Cell_Nonoutlier_SD{5,2} =Index_Mean_Depth_Nonoutlier_SD;
[sv,si] = sort(cell2mat(Cell_Nonoutlier_SD(:,1)));
intersect_set1 = intersect(Cell_Nonoutlier_SD{si(1),2},Cell_Nonoutlier_SD{si(2),2});
intersect_set2 = intersect(intersect_set1,Cell_Nonoutlier_SD{si(3),2});
intersect_set3 = intersect(intersect_set2,Cell_Nonoutlier_SD{si(4),2});
intersect_set_final = intersect(intersect_set3,Cell_Nonoutlier_SD{si(5),2});
intersect_set_final = intersect(intersect_set_final,find(X_exploratory_surveyed_data_discharge_bankfull>0));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if length(intersect_set_final) < 5
    clearvars -except DailyData i_SurvayedData start_path ...
        input_directory ...
        output_directory ...
        functionsdirectory_name ...
        input_files ...
        input_directory ...
        output_files ...
        input_fileIndex ...
        output_fileIndex ...
        cfs_to_cms_unit_conv ...
        ft_to_m_unit_conv  ...
        discharge_unit_label ...
        gageheight_unit_label ...
        Output_suffix ...
        velocity_unit_label ...
        area_unit_label ...
        topwidth_unit_label ...
        mean_depth_unit_label ...
        USGS_Data_Assembled_Fields_proper_sites ...
        Surveyed_Data_Raw_Varialbe_Name ...
        Title_String_suffix ...
        NAME_surveyed_data_parts
    handel = 0;
    error(sprintf('%s, has NOT been saved. \n Number of proper field surveyed data are less than 10 simultanous discharge vs. all the hydraulic measures.',[NAME_surveyed_data_parts{1,1} '_usgs_site']));
end
%%% 3. Finalizing Fitted Power-law Functions %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% 3.1. Setting Fitting Initials %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
s1 = fitoptions('Method','NonlinearLeastSquares',...
    'Lower',[0.0001 -0.01],... % lower limits of fitting parameters
    'Upper',[100 1], ... % upper limits of fitting parameters
    'Startpoint',[0.0001 -0.01]); % starting point of numerical experiments
f1 = fittype('a*(x^b)','coefficients',{'a','b'},'independent','x','options', s1);  % fitting function type
s2 = fitoptions('Method','NonlinearLeastSquares',...
    'Lower',[-10 0.001 -0.01],... % lower limits of fitting parameters
    'Upper',[10 1000 1], ... % upper limits of fitting parameters
    'Startpoint',[0.0001 0.001 -0.01]); % starting point of numerical experiments
f2 = fittype('a*(x^b)+c','coefficients',{'c','a','b'},'independent','x','options', s2); % fitting function type
%%% 3.2. Surveyed Data Gage Height vs. Discharge Plot %%%%%%%%%%%%%%%%%%%%%
[f_fullts_best_model_SD_StgHght_Proper,gness_fullts_best_model_SD_StgHght_Proper] = ...
    fit(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
    Y_response_surveyed_data_gage_height_bankfull(intersect_set_final),...
    f2);
%%% 3.3. Surveyed Data Discharge vs. Velocity %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[f_fullts_best_model_SD_Vel_Proper,gness_fullts_best_model_SD_Vel_Proper] = ...
    fit(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
    Y_response_Velocity_surveyed_data_bankfull(intersect_set_final),...
    f1);
%%% 3.4. Surveyed Data Discharge vs. Width %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[f_fullts_best_model_SD_TpWid_Proper,gness_fullts_best_model_SD_TpWid_Proper] = ...
    fit(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
    Y_response_TopWidth_surveyed_data_bankfull(intersect_set_final),...
    f1);
%%% 3.5. Surveyed Data Discharge vs. Area %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[f_fullts_best_model_SD_Area_Proper,gness_fullts_best_model_SD_Area_Proper] = ...
    fit(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
    Y_response_Area_surveyed_data_bankfull(intersect_set_final),...
    f1);
%%% 3.6. Surveyed Data Discharge vs. Mean Depth %%%%%%%%%%%%%%%%%%%%%%%%%%%
[f_fullts_best_model_SD_Mean_Depth_Proper,gness_fullts_best_model_SD_Mean_Depth_Proper] = ...
    fit(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
    Y_response_Mean_Depth_surveyed_data_bankfull(intersect_set_final),...
    f1);
%%% 4. Plotting %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
all_figs = figure;
set(all_figs ,'visible','off');
if max(X_exploratory_surveyed_data_discharge_bankfull) > 1
    X_exploratory_surveyed_data_discharge_upperlimit = ...
        round(1.025*max(X_exploratory_surveyed_data_discharge_bankfull),0);
else
    X_exploratory_surveyed_data_discharge_upperlimit = ...
        round(1+10*max(X_exploratory_surveyed_data_discharge_bankfull))/10;
end
X_exploratory_surveyed_data_discharge_2 = ...
    0:X_exploratory_steps:X_exploratory_surveyed_data_discharge_upperlimit;
%%% 4.1. Surveyed Data Gage Height vs. Discharge Plot %%%%%%%%%%%%%%%%%%%%%
for I=1:1
    left = 0.295;
    bottom = 0.715;
    width = 0.425;
    height = 0.274; % which is also bottom1-bottom2
    axes('Position',[left bottom width height]);
    ci_SD_fit_Final = confint(f_fullts_best_model_SD_StgHght_Proper);
    c_coefficient = f_fullts_best_model_SD_StgHght_Proper.a;
    f_exponent = f_fullts_best_model_SD_StgHght_Proper.b;
    Intercept_point_estimate = f_fullts_best_model_SD_StgHght_Proper.c;
    StageHeigth_mean_point_estimate_surveyed_data = ...
        c_coefficient.*X_exploratory_surveyed_data_discharge_2'...
        .^f_exponent+Intercept_point_estimate;
    plot(X_exploratory_surveyed_data_discharge_bankfull,...
        Y_response_surveyed_data_gage_height_bankfull,...
        '.','MarkerSize',original_point_shape_size,'Color',all_point_color);
    hold on
    plot_1 = plot(NaN,NaN,'.','Color',all_point_color,...
        'markersize',legend_marker_size);
    %%% based on Daily Data
    plot(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
        Y_response_surveyed_data_gage_height_bankfull(intersect_set_final),...
        '.','MarkerSize',Nonoutlier_point_shape_size ,...
        'Color',proper_bounds_point_color);
    plot_2 = plot(NaN,NaN,'.','Color',proper_bounds_point_color,...
        'markersize',legend_marker_size);
    plot_3 = plot(X_exploratory_surveyed_data_discharge_2,...
        StageHeigth_mean_point_estimate_surveyed_data,...
        '--','Color',proper_bounds_point_color-[0,0.1,0.1],'linewidth',line_width);
    Title_String = ['Disch. vs. Stage, Within Bankfull Stage',...
        Title_String_suffix,' - ', ...
        NAME_surveyed_data_parts{1,1}];
    title(Title_String,'FontSize',Title_String_size);
    %xlabel(['Discharge ', discharge_unit_label],'FontSize',xlabel_FontSize);
    ylabel(['Stage-Height, H ', gageheight_unit_label],'FontSize',ylabel_FontSize);
    set(gca,'FontSize',axes_FontSize); %findobj('type','axes')
    %%% Axes scales
    %upper_discharge_axis_limit = X_exploratory_upperlimit;
    if max(Y_response_surveyed_data_gage_height_bankfull) > 1
        upper_water_depth_axis_limit = round(1.025*max(Y_response_surveyed_data_gage_height_bankfull),0);
    else
        upper_water_depth_axis_limit = round(1+10*max(Y_response_surveyed_data_gage_height_bankfull))/10;
    end
    set(gca, 'XLim', [0, X_exploratory_surveyed_data_discharge_upperlimit ]);
    set(gca, 'YLim', [0, upper_water_depth_axis_limit]);
    %%%
    hold off
    Text_Surveyed_Data_Observered_Reliable_Measures = [...
        'Reliable Flow Measures, meas.counts = ' ...
        num2str(...
        size(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),1),4)];
    Text_Surveyed_Data_Observered_NonReliable_Measures = [...
        'Full Time-Series, meas.counts = ' ...
        num2str(...
        size(Y_response_Velocity_surveyed_data_bankfull,1),4)];
    Text_Survyd_Data_Proper_Peak_Flows_fitted_power_function_compo = [...
        'H=c''{Q^f}+{H_0}, f = ' , ...
        num2str(f_exponent,'%.3f') ...
        ', c'' = ' num2str(c_coefficient,'%.3f') ...
        ', {H_0} = ', num2str(Intercept_point_estimate,'%.3f') ...
        ', R^2 = ' ...
        num2str(gness_fullts_best_model_SD_StgHght_Proper.rsquare,2)];
    hleg_2 = legend([plot_1,plot_2,plot_3],...
        Text_Surveyed_Data_Observered_NonReliable_Measures,...
        Text_Surveyed_Data_Observered_Reliable_Measures,...
        Text_Survyd_Data_Proper_Peak_Flows_fitted_power_function_compo,...
        'Location','SouthEast');
    set(hleg_2,'FontSize',legend_font_size);
    set(hleg_2, 'Box', 'on')
    clear Text_Surveyed_Data_Observered_Reliable_Measures ...
        Text_Surveyed_Data_Observered_out_of_bounds ...
        Text_Survyd_Data_Proper_Peak_Flows_fitted_power_function_compo ...
        hleg_2 plot_1 plot_2
end
%%% 4.2. Surveyed Data Discharge vs. Velocity Plot%%%%%%%%%%%%%%%%%%%%%%%%%
for I=1:1
    left = 0.05;
    bottom = 0.378;%0.373;
    width = 0.425;
    height = 0.274;
    axes('Position',[left bottom width height]);
    ci_SD_f_surveyed_data_Dis_Vel_Proper = confint(f_fullts_best_model_SD_Vel_Proper);
    k_point_estimate_surveyed_data_Dis_Vel = f_fullts_best_model_SD_Vel_Proper.a;
    m_point_estimate_surveyed_data_Dis_Vel = f_fullts_best_model_SD_Vel_Proper.b;
    Velocity_mean_point_estimate_surveyed_data = ...
        k_point_estimate_surveyed_data_Dis_Vel.*X_exploratory_surveyed_data_discharge_2'...
        .^m_point_estimate_surveyed_data_Dis_Vel;
    Title_String = ['Disch. vs. Velocity, Within Bankfull Stage' ...
        Title_String_suffix,' - ', ...
        NAME_surveyed_data_parts{1,1}];
    plot(X_exploratory_surveyed_data_discharge_bankfull,...
        Y_response_Velocity_surveyed_data_bankfull,...
        '.','MarkerSize',original_point_shape_size,'Color',all_point_color);
    hold on
    plot_1 = plot(NaN,NaN,'.','Color',all_point_color,...
        'markersize',legend_marker_size);
    %%% based on Daily Data
    plot(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
        Y_response_Velocity_surveyed_data_bankfull(intersect_set_final),...
        '.','MarkerSize',Nonoutlier_point_shape_size ,...
        'Color',proper_bounds_point_color);
    plot_2 = plot(NaN,NaN,'.','Color',proper_bounds_point_color,...
        'markersize',legend_marker_size);
    plot_3 = plot(X_exploratory_surveyed_data_discharge_2,...
        Velocity_mean_point_estimate_surveyed_data,...
        '--','Color',proper_bounds_point_color-[0,0.1,0.1],'linewidth',line_width);
    title(Title_String,'FontSize',Title_String_size);
    %xlabel(['Discharge ',discharge_unit_label],'FontSize',xlabel_FontSize)
    ylabel(['Velocity, V ',velocity_unit_label],'FontSize',ylabel_FontSize)
    set(gca,'FontSize',axes_FontSize);
    %%% Axes scales
    %upper_discharge_axis_limit = X_exploratory_upperlimit;
    if max(Y_response_Velocity_surveyed_data_bankfull) > 1
        upper_water_depth_axis_limit = round(1.025*max(Y_response_Velocity_surveyed_data_bankfull),2);
    else
        upper_water_depth_axis_limit = round(1+10*max(Y_response_Velocity_surveyed_data_bankfull))/10;
    end
    set(gca, 'XLim', [0, X_exploratory_surveyed_data_discharge_upperlimit ]);
    set(gca, 'YLim', [0, upper_water_depth_axis_limit]);
    %%%
    hold off
    Text_Surveyed_Data_Observered_Reliable_Measures = [...
        'Reliable Flow Measures, meas.counts = ' ...
        num2str(...
        size(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),1),4)];
    Text_Surveyed_Data_Observered_NonReliable_Measures = [...
        'Full Time-Series, meas.counts = ' ...
        num2str(...
        size(Y_response_Velocity_surveyed_data_bankfull,1),4)];
    Text_Surveyed_Data_Observered_fitted_power_function_compo = [...
        'V=k{Q^m}, m = ' , ...
        num2str(m_point_estimate_surveyed_data_Dis_Vel,'%.3f') ...
        ', k = ' ...
        num2str(k_point_estimate_surveyed_data_Dis_Vel,'%.3f') ...
        ', R^2 = ' ...
        num2str(gness_fullts_best_model_SD_Vel_Proper.rsquare,2)];
    hleg_2 = legend([plot_1,plot_2,plot_3],...
        Text_Surveyed_Data_Observered_NonReliable_Measures,...
        Text_Surveyed_Data_Observered_Reliable_Measures,...
        Text_Surveyed_Data_Observered_fitted_power_function_compo,...
        'Location','SouthEast');
    set(hleg_2,'FontSize',legend_font_size);
    set(hleg_2, 'Box', 'on')
    clear Text_Surveyed_Data_Observered_Reliable_Measures ...
        Text_Surveyed_Data_Observered_out_of_bounds ...
        hleg_2 plot_1 plot_2
end
%%% 4.3. Surveyed Data Discharge vs. Width Plot%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for I=1:1
    left = 0.05;
    bottom = 0.0395;%0.0265;
    width = 0.425;
    height = 0.274; % which is also bottom1-bottom2   figure
    axes('Position',[left bottom width height]);
    ci_SD_f_surveyed_data_Dis_Wid_Proper = confint(f_fullts_best_model_SD_TpWid_Proper);
    a_point_estimate_surveyed_data_Dis_Wid = f_fullts_best_model_SD_TpWid_Proper.a;
    b_point_estimate_surveyed_data_Dis_Wid = f_fullts_best_model_SD_TpWid_Proper.b;
    Width_mean_point_estimate_surveyed_data = ...
        a_point_estimate_surveyed_data_Dis_Wid.*X_exploratory_surveyed_data_discharge_2'...
        .^b_point_estimate_surveyed_data_Dis_Wid;
    Title_String = ['Disch. vs. Top-Width, Within Bankfull Stage' ...
        Title_String_suffix,' - ', ...
        NAME_surveyed_data_parts{1,1}];
    plot(X_exploratory_surveyed_data_discharge_bankfull,...
        Y_response_TopWidth_surveyed_data_bankfull,...
        '.','MarkerSize',original_point_shape_size,'Color',all_point_color);
    hold on
    plot_1 = plot(NaN,NaN,'.','Color',all_point_color,...
        'markersize',legend_marker_size);
    %%% based on Daily Data
    plot(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
        Y_response_TopWidth_surveyed_data_bankfull(intersect_set_final),...
        '.','MarkerSize',Nonoutlier_point_shape_size ,...
        'Color',proper_bounds_point_color);
    plot_2 = plot(NaN,NaN,'.','Color',proper_bounds_point_color,...
        'markersize',legend_marker_size);
    plot_3 = plot(X_exploratory_surveyed_data_discharge_2,...
        Width_mean_point_estimate_surveyed_data,...
        '--','Color',proper_bounds_point_color-[0,0.1,0.1],'linewidth',line_width);
    title(Title_String,'FontSize',Title_String_size);
    xlabel(['Discharge, Q ', discharge_unit_label],'FontSize',xlabel_FontSize)
    ylabel(['Top-Width, W ', topwidth_unit_label],'FontSize',ylabel_FontSize)
    set(gca,'FontSize',axes_FontSize);
    
    %%% Axes scales
    %upper_discharge_axis_limit = X_exploratory_upperlimit;
    if max(Y_response_TopWidth_surveyed_data_bankfull) > 1
        upper_water_depth_axis_limit = round(1.025*max(Y_response_TopWidth_surveyed_data_bankfull),0);
    else
        upper_water_depth_axis_limit = round(1+10*max(Y_response_TopWidth_surveyed_data_bankfull))/10;
    end
    set(gca, 'XLim', [0, X_exploratory_surveyed_data_discharge_upperlimit ]);
    set(gca, 'YLim', [0, upper_water_depth_axis_limit]);
    %%%
    hold off
    Text_Surveyed_Data_Observered_Reliable_Measures = [...
        'Reliable Flow Measures, meas.counts = ' ...
        num2str(...
        size(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),1),4)];
    Text_Surveyed_Data_Observered_NonReliable_Measures = [...
        'Full Time-Series, meas.counts = ' ...
        num2str(...
        length(Y_response_TopWidth_surveyed_data_bankfull),4)];
    Text_Surveyed_Data_Observered_fitted_power_function_compo = [...
        'W=a{Q^b}, b = ' , ...
        num2str(b_point_estimate_surveyed_data_Dis_Wid,'%.3f') ...
        ', a = ' ...
        num2str(a_point_estimate_surveyed_data_Dis_Wid,'%.3f') ...
        ', R^2 = ' ...
        num2str(gness_fullts_best_model_SD_TpWid_Proper.rsquare,2)];
    hleg_2 = legend([plot_1,plot_2,plot_3],...
        Text_Surveyed_Data_Observered_NonReliable_Measures,...
        Text_Surveyed_Data_Observered_Reliable_Measures,...
        Text_Surveyed_Data_Observered_fitted_power_function_compo,...
        'Location','SouthEast');
    set(hleg_2,'FontSize',legend_font_size);
    set(hleg_2, 'Box', 'on')
    
    clear Text_Surveyed_Data_Observered_Reliable_Measures ...
        Text_Surveyed_Data_Observered_out_of_bounds ...
        hleg_2 plot_1 plot_2
end
%%% 4.4. Surveyed Data Discharge vs. Area Plot%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for I=1:1
    left = 0.542;
    bottom = 0.378;%0.373;
    width = 0.425;
    height = 0.274; % which is also bottom1-bottom2  figure
    axes('Position',[left bottom width height]);
    ci_SD_f_surveyed_data_Dis_Area_Proper = confint(f_fullts_best_model_SD_Area_Proper);
    s_point_estimate_surveyed_data_Dis_Area = f_fullts_best_model_SD_Area_Proper.a;
    r_point_estimate_surveyed_data_Dis_Area = f_fullts_best_model_SD_Area_Proper.b;
    Area_mean_point_estimate_surveyed_data = ...
        s_point_estimate_surveyed_data_Dis_Area.*X_exploratory_surveyed_data_discharge_2'...
        .^r_point_estimate_surveyed_data_Dis_Area;
    Title_String = [...
        'Disch. vs. Flow Area, Within Bankfull Stage' ...
        Title_String_suffix,' - ', ...
        NAME_surveyed_data_parts{1,1}];
    plot(X_exploratory_surveyed_data_discharge_bankfull,...
        Y_response_Area_surveyed_data_bankfull,...
        '.','MarkerSize',original_point_shape_size,'Color',all_point_color);
    hold on
    plot_1 = plot(NaN,NaN,'.','Color',all_point_color,...
        'markersize',legend_marker_size);
    %%% based on Daily Data
    plot(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
        Y_response_Area_surveyed_data_bankfull(intersect_set_final),...
        '.','MarkerSize',Nonoutlier_point_shape_size ,...
        'Color',proper_bounds_point_color);
    plot_2 = plot(NaN,NaN,'.','Color',proper_bounds_point_color,...
        'markersize',legend_marker_size);
    plot_3 = plot(X_exploratory_surveyed_data_discharge_2,...
        Area_mean_point_estimate_surveyed_data,...
        '--','Color',proper_bounds_point_color-[0,0.1,0.1],'linewidth',line_width);
    title(Title_String,'FontSize',Title_String_size);
    %xlabel(['Discharge ', discharge_unit_label],'FontSize',xlabel_FontSize)
    ylabel(['Flow Area, A ', area_unit_label],'FontSize',ylabel_FontSize)
    set(gca,'FontSize',axes_FontSize);
    %%% Axes scales
    %upper_discharge_axis_limit = X_exploratory_upperlimit;
    if max(Y_response_Area_surveyed_data_bankfull) > 1
        upper_water_depth_axis_limit = round(1.025*max(Y_response_Area_surveyed_data_bankfull),0);
    else
        upper_water_depth_axis_limit = round(1+10*max(Y_response_Area_surveyed_data_bankfull))/10;
    end
    set(gca, 'XLim', [0, X_exploratory_surveyed_data_discharge_upperlimit ]);
    set(gca, 'YLim', [0, upper_water_depth_axis_limit]);
    %%%
    hold off
    Text_Surveyed_Data_Observered_Reliable_Measures = [...
        'Reliable Flow Measures, meas.counts = ' ...
        num2str(...
        size(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),1),4)];
    Text_Surveyed_Data_Observered_NonReliable_Measures = [...
        'Full Time-Series, meas.counts = ' ...
        num2str(...
        length(Y_response_Area_surveyed_data_bankfull),4)];
    Text_Surveyed_Data_Observered_fitted_power_function_compo = [...
        'A=s{Q^r}, r = ' , ...
        num2str(r_point_estimate_surveyed_data_Dis_Area,'%.3f') ...
        ', s = ' ...
        num2str(s_point_estimate_surveyed_data_Dis_Area,'%.3f') ...
        ', R^2 = ' ...
        num2str(gness_fullts_best_model_SD_Area_Proper.rsquare,2)];
    hleg_2 = legend([plot_1,plot_2,plot_3],...
        Text_Surveyed_Data_Observered_NonReliable_Measures,...
        Text_Surveyed_Data_Observered_Reliable_Measures,...
        Text_Surveyed_Data_Observered_fitted_power_function_compo,...
        'Location','SouthEast');
    set(hleg_2,'FontSize',legend_font_size);
    set(hleg_2, 'Box', 'on')
    clear Text_Surveyed_Data_Observered_Reliable_Measures ...
        Text_Surveyed_Data_Observered_out_of_bounds ...
        hleg_2 plot_1 plot_2
end
%%% 4.5. Surveyed Data Discharge vs. Mean Depth Plot%%%%%%%%%%%%%%%%%%%%%%%
for I=1:1
    left = 0.542;
    bottom = 0.0395; %0.0265;
    width = 0.425;
    height = 0.274; % which is also bottom1-bottom2 figure
    axes('Position',[left bottom width height]);
    ci_SD_f_surveyed_data_Dis_Mean_Depth_Proper = confint(f_fullts_best_model_SD_Mean_Depth_Proper);
    cprime_point_estimate_surveyed_data_Dis_Mean_Dth = f_fullts_best_model_SD_Mean_Depth_Proper.a;
    f_point_estimate_surveyed_data_Dis_Mean_Dth = f_fullts_best_model_SD_Mean_Depth_Proper.b;
    Mean_Depth_mean_point_estimate_surveyed_data = ...
        cprime_point_estimate_surveyed_data_Dis_Mean_Dth.*...
        X_exploratory_surveyed_data_discharge_2'...
        .^f_point_estimate_surveyed_data_Dis_Mean_Dth;
    Title_String = ['Disch. vs. Mean Depth, Within Bankfull Stage' ...
        Title_String_suffix,' - ', ...
        NAME_surveyed_data_parts{1,1}];
    plot(X_exploratory_surveyed_data_discharge_bankfull,...
        Y_response_Mean_Depth_surveyed_data_bankfull,...
        '.','MarkerSize',original_point_shape_size,'Color',all_point_color);
    hold on
    plot_1 = plot(NaN,NaN,'.','Color',all_point_color,...
        'markersize',legend_marker_size);
    %%% based on Daily Data
    plot(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),...
        Y_response_Mean_Depth_surveyed_data_bankfull(intersect_set_final),...
        '.','MarkerSize',Nonoutlier_point_shape_size ,...
        'Color',proper_bounds_point_color);
    plot_2 = plot(NaN,NaN,'.','Color',proper_bounds_point_color,...
        'markersize',legend_marker_size);
    plot_3 = plot(X_exploratory_surveyed_data_discharge_2,...
        Mean_Depth_mean_point_estimate_surveyed_data,...
        '--','Color',proper_bounds_point_color-[0,0.1,0.1],'linewidth',line_width);
    title(Title_String,'FontSize',Title_String_size);
    xlabel(['Discharge, Q ',discharge_unit_label],'FontSize',xlabel_FontSize)
    ylabel(['Mean Water Depth, Y ', mean_depth_unit_label],'FontSize',ylabel_FontSize)
    set(gca,'FontSize',axes_FontSize);
    %%% Axes scales
    %upper_discharge_axis_limit = X_exploratory_upperlimit;
    if max(Y_response_Mean_Depth_surveyed_data_bankfull) > 1
        upper_water_depth_axis_limit = round(1.025*max(Y_response_Mean_Depth_surveyed_data_bankfull),0);
    else
        upper_water_depth_axis_limit = round(1+10*max(Y_response_Mean_Depth_surveyed_data_bankfull))/10;
    end
    set(gca, 'XLim', [0, X_exploratory_surveyed_data_discharge_upperlimit ]);
    set(gca, 'YLim', [0, upper_water_depth_axis_limit]);
    %%%
    hold off
    Text_Surveyed_Data_Observered_Reliable_Measures = [...
        'Reliable Flow Measures, meas.counts = ' ...
        num2str(...
        size(X_exploratory_surveyed_data_discharge_bankfull(intersect_set_final),1),4)];
    Text_Surveyed_Data_Observered_NonReliable_Measures = [...
        'Full Time-Series, meas.counts = ' ...
        num2str(...
        length(Y_response_Mean_Depth_surveyed_data_bankfull),4)];
    Text_Surveyed_Data_Observered_fitted_power_function_compo = [...
        'Y=c{Q^f}, f = ' , ...
        num2str(f_point_estimate_surveyed_data_Dis_Mean_Dth,'%.3f') ...
        ', c = ' ...
        num2str(cprime_point_estimate_surveyed_data_Dis_Mean_Dth,'%.3f') ...
        ', R^2 = ' ...
        num2str(gness_fullts_best_model_SD_Mean_Depth_Proper.rsquare,2)];
    hleg_2 = legend([plot_1,plot_2,plot_3],...
        Text_Surveyed_Data_Observered_NonReliable_Measures,...
        Text_Surveyed_Data_Observered_Reliable_Measures,...
        Text_Surveyed_Data_Observered_fitted_power_function_compo,...
        'Location','SouthEast');
    set(hleg_2,'FontSize',legend_font_size);
    set(hleg_2, 'Box', 'on')
    clear Text_Surveyed_Data_Observered_Reliable_Measures ...
        Text_Surveyed_Data_Observered_out_of_bounds ...
        hleg_2 plot_1 plot_2
end
output_fileName = ...
    fullfile(output_directory,...
    strcat(NAME_surveyed_data_parts{1,1},'_usgs_site_AHG'));
all_figs.PaperOrientation = 'landscape';
all_figs.Position = [680 289 760 530];
print(all_figs,'-dpdf',output_fileName)
close(all_figs)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% 5. Computing the continuity based upon ack and bfm parameters
% a c k
%%% Reliable Flow Measures
AHG_coeff_product_Reliable_Flow_Meas = f_fullts_best_model_SD_TpWid_Proper.a * ...
    f_fullts_best_model_SD_Mean_Depth_Proper.a * ...
    f_fullts_best_model_SD_Vel_Proper.a;
% b f m
%%% Reliable Flow Measures
AHG_expn_sum_Reliable_Flow_Meas = f_fullts_best_model_SD_TpWid_Proper.b + ...
    f_fullts_best_model_SD_Mean_Depth_Proper.b + ...
    f_fullts_best_model_SD_Vel_Proper.b;
% beta shape exponent
%%% Reliable Flow Measures
beta_shape_expn_Reliable_Flow_Meas = f_fullts_best_model_SD_Mean_Depth_Proper.b/...
    f_fullts_best_model_SD_TpWid_Proper.b;
% p hydraulic radius exponent
%%% Reliable Flow Measures
p_HRexpn_Reliable_Flow_Meas = f_fullts_best_model_SD_Vel_Proper.b/...
    f_fullts_best_model_SD_Mean_Depth_Proper.b;
% alpha shape coefficient
%%% Reliable Flow Measures
alpha_shape_expn_Reliable_Flow_Meas = ...
    f_fullts_best_model_SD_Mean_Depth_Proper.a*...
    (1+1/(beta_shape_expn_Reliable_Flow_Meas))/...
    (f_fullts_best_model_SD_TpWid_Proper.a^beta_shape_expn_Reliable_Flow_Meas);
% manning*(energy slope)^-q
%%% Reliable Flow Measures
manning_energyslope_product_Reliable_Flow_Meas = ...
    (f_fullts_best_model_SD_Mean_Depth_Proper.a^...
    (p_HRexpn_Reliable_Flow_Meas+1))*...
    f_fullts_best_model_SD_TpWid_Proper.a;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% 6. It generates string containing the trail of site numbers separated by ","
site_no_sequence_string = NAME_surveyed_data_parts{1,1};

Imported_Data_String = webread(strcat('http://waterdata.usgs.gov/nwis/measurements?multiple_site_no=',...
    site_no_sequence_string,...
    '&group_key=NONE&format=sitefile_output&sitefile_output_format=rdb&column_name=site_no&column_name=dec_lat_va&column_name=dec_long_va&column_name=drain_area_va&set_logscale_y=1&channel_html_info=0&date_format=YYYY-MM-DD&channel_rdb_info=0&rdb_compression=file&list_of_search_criteria=multiple_site_no'));

coordi_drainagearea = textscan(Imported_Data_String,...
    '%s %f %f %s %s %f',...
    'delimiter','\t',...
    'headerlines',27,...
    'CommentStyle', '#');

USGS_Data_Assembled_Fields_values_proper_sites = {...
    'UGSS',... % 'agency_cd'
    NAME_surveyed_data_parts{1,1},... % 'site_no'
    coordi_drainagearea{1,2},... % 'lat_va'
    coordi_drainagearea{1,3},... % 'long_va'
    2.58999*coordi_drainagearea{1,end},... % 'drain_area_va' 2.58999 factor is applied for mile2 to km2 conversion ; %Mean_Annual_Discharge,... % 'MeanQ'
    size(intersect_set_final,1),... % 'SD Reliable_Flow_Meas_Counts'
    size(Y_response_surveyed_data_gage_height_bankfull,1),... % 'SD Full_TimeSeries_Meas_Counts'
    [f_exponent,ci_SD_fit_Final(1,2),ci_SD_fit_Final(2,2)],... % 'sd_gagehei_disch_exp' reliable/fulltimeseries
    [c_coefficient,ci_SD_fit_Final(1,1),ci_SD_fit_Final(2,1)],... % 'sd_gagehei_disch_coeff' reliable/fulltimeseries
    [Intercept_point_estimate,ci_SD_fit_Final(1,3),ci_SD_fit_Final(2,3)],... % 'sd_gagehei_disch_offset' reliable/fulltimeseries
    gness_fullts_best_model_SD_StgHght_Proper.rsquare,... % 'dd_gagehei_disch_R2' reliable/fulltimeseries
    [m_point_estimate_surveyed_data_Dis_Vel,ci_SD_f_surveyed_data_Dis_Vel_Proper(1,2),ci_SD_f_surveyed_data_Dis_Vel_Proper(2,2)],... % 'sd_vel_disch_exp' reliable/fulltimeseries
    [k_point_estimate_surveyed_data_Dis_Vel,ci_SD_f_surveyed_data_Dis_Vel_Proper(1,1),ci_SD_f_surveyed_data_Dis_Vel_Proper(2,1)],... % 'sd_vel_disch_coeff' reliable/fulltimeseries
    gness_fullts_best_model_SD_Vel_Proper.rsquare,... % 'sd_vel_disch_R2' reliable/fulltimeseries
    [r_point_estimate_surveyed_data_Dis_Area,ci_SD_f_surveyed_data_Dis_Area_Proper(1,2),ci_SD_f_surveyed_data_Dis_Area_Proper(2,2)],... % 'sd_area_disch_exp' reliable/fulltimeseries
    [s_point_estimate_surveyed_data_Dis_Area,ci_SD_f_surveyed_data_Dis_Area_Proper(1,1),ci_SD_f_surveyed_data_Dis_Area_Proper(2,1)],... % 'sd_area_disch_coeff' reliable/fulltimeseries
    gness_fullts_best_model_SD_Area_Proper.rsquare,... % 'sd_area_disch_R2' reliable/fulltimeseries
    [b_point_estimate_surveyed_data_Dis_Wid,ci_SD_f_surveyed_data_Dis_Wid_Proper(1,2),ci_SD_f_surveyed_data_Dis_Wid_Proper(2,2)],... % 'sd_width_disch_exp' reliable/fulltimeseries
    [a_point_estimate_surveyed_data_Dis_Wid,ci_SD_f_surveyed_data_Dis_Wid_Proper(1,1),ci_SD_f_surveyed_data_Dis_Wid_Proper(2,1)],... % 'sd_width_disch_coeff' reliable/fulltimeseries
    gness_fullts_best_model_SD_TpWid_Proper.rsquare,... % 'sd_width_disch_R2' reliable/fulltimeseries
    [f_point_estimate_surveyed_data_Dis_Mean_Dth,ci_SD_f_surveyed_data_Dis_Mean_Depth_Proper(1,2),ci_SD_f_surveyed_data_Dis_Mean_Depth_Proper(2,2)],... % 'sd_mdepth_disch_exp' reliable/fulltimeseries
    [cprime_point_estimate_surveyed_data_Dis_Mean_Dth,ci_SD_f_surveyed_data_Dis_Mean_Depth_Proper(1,1),ci_SD_f_surveyed_data_Dis_Mean_Depth_Proper(2,1)],... % 'sd_mdepth_disch_coeff' reliable/fulltimeseries
    gness_fullts_best_model_SD_Mean_Depth_Proper.rsquare,... % 'sd_mdepth_disch_R2' reliable/fulltimeseries
    AHG_expn_sum_Reliable_Flow_Meas,... % 'AHG Exponents Sum' reliable/fulltimeseries
    AHG_coeff_product_Reliable_Flow_Meas,... % 'AHG Coeff. Product' reliable/fulltimeseries
    alpha_shape_expn_Reliable_Flow_Meas,... % 'Alpha Point Estimate' reliable/fulltimeseries
    beta_shape_expn_Reliable_Flow_Meas,... % 'Beta Point Estimate' reliable/fulltimeseries
    p_HRexpn_Reliable_Flow_Meas,... % 'p Exponent Point Estimate' reliable/fulltimeseries
    manning_energyslope_product_Reliable_Flow_Meas,... % 'manning_energyslope_product' reliable/fulltimeseries
    };
USGS_Data_AHG_Table = [...
    USGS_Data_AHG_Table;...
    USGS_Data_Assembled_Fields_values_proper_sites];

matfile = fullfile(output_directory, strcat(NAME_surveyed_data_parts{1,1},'_usgs_site_AHG'));
save(matfile,'USGS_Data_AHG_Table');
handel = 1;
fprintf('At-A-Station Hydraulic Geometry relations and plots of USGS site no. %s has been successfully calculated. \n',NAME_surveyed_data_parts{1,1});

clearvars -except DailyData i_SurvayedData start_path ...
    input_directory ...
    output_directory ...
    functionsdirectory_name ...
    input_files ...
    input_directory ...
    output_files ...
    input_fileIndex ...
    output_fileIndex ...
    cfs_to_cms_unit_conv ...
    ft_to_m_unit_conv  ...
    discharge_unit_label ...
    gageheight_unit_label ...
    Output_suffix ...
    velocity_unit_label ...
    area_unit_label ...
    topwidth_unit_label ...
    mean_depth_unit_label ...
    USGS_Data_Assembled_Fields_proper_sites ...
    Surveyed_Data_Raw_Varialbe_Name ...
    Title_String_suffix ...
    NAME_surveyed_data_parts
%%
end